// firebase-config.js
// ─────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED by build.js during Vercel deployment.
// The real values are injected from Vercel Environment Variables.
//
// For LOCAL development:
//   Replace the placeholder values below with your real Firebase credentials.
//   Get them from: Firebase Console → Project Settings → Your Apps → Config
//
// ⚠️  Never commit real API keys to a public repo.
//     Keep this file with placeholders in git; Vercel injects real values at build time.
// ─────────────────────────────────────────────────────────

window.__FIREBASE_CONFIG__ = {
  apiKey: "AIzaSyAqpysnl78qADzbqFRJTaAJDFgdpkaM69Q",
  authDomain: "conflow-3b54f.firebaseapp.com",
  projectId: "conflow-3b54f",
  storageBucket: "conflow-3b54f.firebasestorage.app",
  messagingSenderId: "388982797314",
  appId: "1:388982797314:web:0954d4da25800b7deee31b",
  measurementId: "G-RMRSD6QSLM"
};